### ISSUE TITLE
Overlap Boundary ist doch jetzt nach SQLite einführung falsch oder?? 

### ISSUE THREAD

**Issue by Lukas-Dresel** [cliffTifflor/GarbageCollector#6]
Nachdem OVERLAPPINGBOUNDER (falsch geschrieben, aber egal) nach den Kommentaren die Laenge des laengsten Patterns ist, muesste das doch jetzt mit 16 Byte SQLite Header auch 16 sein.

Ausserdem, sollten wir das dynamisch berechnen, wenn wir die Module leichter hinzuzufuegen machen wollen.

**Comment by btlorch** [comment]
You're right. The overlap is now equal to the length of the longest pattern to be matched.
